/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxa/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxa/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchTaxa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxa/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTaxon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxa/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTaxonMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getImportStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/taxa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTaxon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/taxa/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateTaxon"];
        post?: never;
        delete: operations["deleteTaxon"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/taxa/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveTaxon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/taxa/{taxonId}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadTaxonMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/taxa/{taxonId}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateTaxonMedia"];
        post?: never;
        delete: operations["deleteTaxonMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TaxonRank: "KINGDOM" | "SUBKINGDOM" | "PHYLUM" | "SUBPHYLUM" | "CLASS" | "SUBCLASS" | "ORDER" | "SUBORDER" | "SUPERFAMILY" | "FAMILY" | "SUBFAMILY" | "TRIBE" | "GENUS" | "SUBGENUS" | "SPECIES" | "SUBSPECIES" | "VARIETY" | "FORM" | "OTHER";
        TaxonListItem: {
            /** Format: int64 */
            id: number;
            rank: components["schemas"]["TaxonRank"];
            scientificName: string;
            commonName?: string | null;
            /** @description Visible children for current view */
            childCount: number;
            hasChildren: boolean;
            rankRaw?: string | null;
            /** @description Physical direct child count */
            directChildCount: number;
            /** @description Simple-view unclassified bucket */
            placeholder?: boolean;
        };
        TaxonBreadcrumb: {
            /** Format: int64 */
            id: number;
            rank: components["schemas"]["TaxonRank"];
            scientificName: string;
            commonName?: string | null;
        };
        TaxonMedia: {
            /** Format: int64 */
            id: number;
            url: string;
            mimeType?: string | null;
            width?: number | null;
            height?: number | null;
            sortOrder?: number;
            locale?: string | null;
            caption?: string | null;
            license?: string | null;
            attribution?: string | null;
        };
        TaxonSynonym: {
            /** Format: int64 */
            id: number;
            scientificName: string;
        };
        TaxonDetail: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            parentId?: number | null;
            rank: components["schemas"]["TaxonRank"];
            scientificName: string;
            scientificNameAuthorship?: string | null;
            scientificNameVerbatim?: string | null;
            namePublishedIn?: string | null;
            nameAccordingTo?: string | null;
            nomenclaturalCode?: string | null;
            nomenclaturalStatus?: string | null;
            commonName?: string | null;
            summary?: string | null;
            description?: string | null;
            locale: string;
            /** @description Visible children for current view */
            childCount: number;
            accepted: boolean;
            breadcrumbs: components["schemas"]["TaxonBreadcrumb"][];
            media: components["schemas"]["TaxonMedia"][];
            /** Format: int64 */
            mediaTotal: number;
            synonyms: components["schemas"]["TaxonSynonym"][];
            rankRaw?: string | null;
            vernaculars: components["schemas"]["TaxonVernacular"][];
            distributions: components["schemas"]["TaxonDistribution"][];
            directChildCount: number;
            /** Format: int64 */
            nearestSimpleAncestorId?: number | null;
            /** @description Simple-view unclassified bucket */
            placeholder?: boolean;
        };
        TaxonVernacular: {
            locale: string;
            commonName: string;
            preferred: boolean;
        };
        TaxonDistribution: {
            /** Format: int64 */
            id: number;
            countryCode?: string | null;
            locality?: string | null;
            establishmentMeans?: string | null;
            threatStatus?: string | null;
            sourceText?: string | null;
        };
        PageTaxonListItem: {
            items: components["schemas"]["TaxonListItem"][];
            /** Format: int64 */
            total: number;
            page: number;
            size: number;
        };
        PageTaxonMedia: {
            items: components["schemas"]["TaxonMedia"][];
            /** Format: int64 */
            total: number;
            page: number;
            size: number;
        };
        StatsSummary: {
            /** Format: int64 */
            totalTaxa: number;
            byRank: {
                [key: string]: number;
            };
            byKingdom: {
                [key: string]: number;
            };
            dataset?: components["schemas"]["DatasetCitation"];
        };
        DatasetCitation: {
            title?: string | null;
            version?: string | null;
            sourceUrl?: string | null;
            /** Format: date-time */
            importedAt?: string | null;
        };
        CreateTaxonRequest: {
            /** Format: int64 */
            parentId?: number | null;
            rank: components["schemas"]["TaxonRank"];
            scientificName: string;
            locale?: string;
            commonName?: string;
            summary?: string;
            description?: string;
        };
        UpdateTaxonRequest: {
            scientificName: string;
            accepted?: boolean;
            locale?: string;
            commonName?: string;
            summary?: string;
            description?: string;
        };
        ApiResponseHealth: {
            code?: number;
            message?: string;
            data?: {
                status?: string;
            };
        };
        ApiResponseStatsSummary: {
            code?: number;
            message?: string;
            data?: components["schemas"]["StatsSummary"];
        };
        ApiResponsePageTaxonListItem: {
            code?: number;
            message?: string;
            data?: components["schemas"]["PageTaxonListItem"];
        };
        ApiResponsePageTaxonMedia: {
            code?: number;
            message?: string;
            data?: components["schemas"]["PageTaxonMedia"];
        };
        ApiResponseTaxonDetail: {
            code?: number;
            message?: string;
            data?: components["schemas"]["TaxonDetail"];
        };
        ApiResponseTaxonMedia: {
            code?: number;
            message?: string;
            data?: components["schemas"]["TaxonMedia"];
        };
        ApiResponseUsername: {
            code?: number;
            message?: string;
            data?: {
                username?: string;
            };
        };
        ApiResponseVoid: {
            code?: number;
            message?: string;
            data?: unknown;
        };
        ImportStatus: {
            jobKey?: string;
            phase?: string;
            /** Format: int64 */
            processedCount?: number;
            /** Format: int64 */
            totalHint?: number;
            detail?: string;
            running?: boolean;
        };
        ApiResponseImportStatus: {
            code?: number;
            message?: string;
            data?: components["schemas"]["ImportStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseHealth"];
                };
            };
        };
    };
    getStatsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseStatsSummary"];
                };
            };
        };
    };
    listChildren: {
        parameters: {
            query?: {
                parentId?: number;
                locale?: string;
                page?: number;
                size?: number;
                view?: "simple" | "full";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageTaxonListItem"];
                };
            };
        };
    };
    searchTaxa: {
        parameters: {
            query: {
                q: string;
                locale?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageTaxonListItem"];
                };
            };
        };
    };
    getTaxon: {
        parameters: {
            query?: {
                locale?: string;
                view?: "simple" | "full";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTaxonDetail"];
                };
            };
        };
    };
    listTaxonMedia: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageTaxonMedia"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUsername"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUsername"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getImportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseImportStatus"];
                };
            };
        };
    };
    createTaxon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaxonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTaxonDetail"];
                };
            };
        };
    };
    updateTaxon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaxonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTaxonDetail"];
                };
            };
        };
    };
    deleteTaxon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    moveTaxon: {
        parameters: {
            query?: {
                locale?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    newParentId: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTaxonDetail"];
                };
            };
        };
    };
    uploadTaxonMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    locale?: string;
                    caption?: string;
                    license?: string;
                    attribution?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTaxonMedia"];
                };
            };
        };
    };
    updateTaxonMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonId: number;
                mediaId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    caption?: string | null;
                    sortOrder?: number | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseTaxonMedia"];
                };
            };
        };
    };
    deleteTaxonMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonId: number;
                mediaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
